import Navigation from "./components/Navigation";
import "./globals.css";
import { Sora } from "next/font/google";

const inter = Sora({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.className} px-4 lg:px-[100px] py-[40px]`}
    >
      <body className={inter.className}>
        <>
          <Navigation />
          {children}
        </>
      </body>
    </html>
  );
}
